// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class PrestashopTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addNewProduct() {
    driver.get("http://localhost:8080/administrator/index.php?controller=AdminLogin&token=6f8e295c6f145407a04731672a4f8b2a");
    driver.manage().window().setSize(new Dimension(1164, 700));
    System.out.println("{ASSESSOR}:LoginPage:doLogin");
    driver.findElement(By.id("email")).sendKeys("admin@prestashop.com");
    driver.findElement(By.id("passwd")).sendKeys("password");
    driver.findElement(By.name("submitLogin")).click();
    System.out.println("{ASSESSOR}:DashboardPage:hoverCatalog");
    System.out.println("{ASSESSOR}:DashboardPage:clickProducts");
    {
      WebElement element = driver.findElement(By.linkText("Catalog"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Products")).click();
    System.out.println("{ASSESSOR}:ProductsPage:clickAddNewProduct");
    driver.findElement(By.cssSelector("#page-header-desc-product-new_product > .process-icon-new")).click();
    js.executeScript("window.scrollTo(0,0)");
    System.out.println("{ASSESSOR}:NewProductPage:changeName");
    driver.findElement(By.id("name_1")).sendKeys("Blue Jacket3");
    System.out.println("{ASSESSOR}:NewProductPage:clickSave");
    driver.findElement(By.name("submitAddproduct")).click();
    System.out.println("{ASSESSOR}:ProductsPage:getData");
    assertThat(driver.findElement(By.cssSelector(".alert-success:nth-child(1)")).getText(), is("×\\\\nSuccessful creation"));
    System.out.println("{ASSESSOR}:ProductsPage:SignOut");
    driver.findElement(By.cssSelector(".employee_name")).click();
    driver.findElement(By.id("header_logout")).click();
  }
  @Test
  public void addEmptyProduct() {
    driver.get("http://localhost:8080/administrator/index.php?controller=AdminLogin&token=6f8e295c6f145407a04731672a4f8b2a");
    driver.manage().window().setSize(new Dimension(1179, 700));
    System.out.println("{ASSESSOR}:LoginPage:doLogin");
    driver.findElement(By.id("email")).sendKeys("admin@prestashop.com");
    driver.findElement(By.id("passwd")).sendKeys("password");
    driver.findElement(By.cssSelector(".ladda-label")).click();
    System.out.println("{ASSESSOR}:DashboardPage:hoverCatalog");
    System.out.println("{ASSESSOR}:DashboardPage:clickProducts");
    {
      WebElement element = driver.findElement(By.linkText("Catalog"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Products")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".addons_connect"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    System.out.println("{ASSESSOR}:ProductsPage:clickAddNewProduct");
    driver.findElement(By.cssSelector("#page-header-desc-product-new_product > div")).click();
    {
      WebElement element = driver.findElement(By.linkText("Help"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    js.executeScript("window.scrollTo(0,0)");
    System.out.println("{ASSESSOR}:NewProductPage:clickSave");
    driver.findElement(By.cssSelector(".panel-footer:nth-child(22) > .btn:nth-child(2) > .process-icon-save")).click();
    js.executeScript("window.scrollTo(0,175.1999969482422)");
    System.out.println("{ASSESSOR}:NewProductPage:getData");
    assertThat(driver.findElement(By.cssSelector("ol > li:nth-child(1)")).getText(), is("This link_rewrite field is required at least in English (English)"));
    System.out.println("{ASSESSOR}:NewProductPage:SignOut");
    driver.findElement(By.cssSelector(".employee_name > .string-short")).click();
    driver.findElement(By.id("header_logout")).click();
  }
  @Test
  public void addEmptyFeature() {
    driver.get("http://localhost:8080/administrator/index.php?controller=AdminLogin&token=6f8e295c6f145407a04731672a4f8b2a");
    driver.manage().window().setSize(new Dimension(1190, 700));
    System.out.println("{ASSESSOR}:LoginPage:doLogin");
    driver.findElement(By.id("email")).sendKeys("admin@prestashop.com");
    driver.findElement(By.id("passwd")).sendKeys("password");
    driver.findElement(By.name("submitLogin")).click();
    System.out.println("{ASSESSOR}:DashboardPage:hoverCatalog");
    {
      WebElement element = driver.findElement(By.linkText("Catalog"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    System.out.println("{ASSESSOR}:DashboardPage:clickProductFeatures");
    driver.findElement(By.linkText("Product Features")).click();
    System.out.println("{ASSESSOR}:ProductFeaturesPage:clickAddFeature");
    driver.findElement(By.cssSelector("#page-header-desc-feature-new_feature > div")).click();
    System.out.println("{ASSESSOR}:NewFeaturePage:clickSave");
    driver.findElement(By.id("feature_form_submit_btn")).click();
    System.out.println("{ASSESSOR}:NewFeaturePage:getData");
    assertThat(driver.findElement(By.cssSelector(".alert-danger")).getText(), is("×\\\\nThe field name is required at least in English (English)."));
    System.out.println("{ASSESSOR}:NewFeaturePage:SignOut");
    driver.findElement(By.cssSelector(".employee_name > .string-short")).click();
    driver.findElement(By.id("header_logout")).click();
  }
  @Test
  public void addEmptyState() {
    driver.get("http://localhost:8080/administrator/index.php?controller=AdminLogin&token=6f8e295c6f145407a04731672a4f8b2a");
    driver.manage().window().setSize(new Dimension(1215, 700));
    System.out.println("{ASSESSOR}:LoginPage:doLogin");
    driver.findElement(By.id("email")).sendKeys("admin@prestashop.com");
    driver.findElement(By.id("passwd")).sendKeys("password");
    driver.findElement(By.name("submitLogin")).click();
    System.out.println("{ASSESSOR}:DashboardPage:hoverLocalization");
    {
      WebElement element = driver.findElement(By.linkText("Localization"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    System.out.println("{ASSESSOR}:DashboardPage:clickStates");
    driver.findElement(By.linkText("States")).click();
    System.out.println("{ASSESSOR}:StatesPage:clickAddNewState");
    driver.findElement(By.cssSelector("#page-header-desc-state-new_state > .process-icon-new")).click();
    System.out.println("{ASSESSOR}:NewStatePage:clickSave");
    driver.findElement(By.cssSelector(".process-icon-save")).click();
    System.out.println("{ASSESSOR}:NewStatePage:getData");
    assertThat(driver.findElement(By.cssSelector("ol > li:nth-child(2)")).getText(), is("The name field is required."));
    System.out.println("{ASSESSOR}:NewStatePage:SignOut");
    driver.findElement(By.cssSelector(".employee_name > .string-long")).click();
    driver.findElement(By.id("header_logout")).click();
  }
  @Test
  public void addNewAttribute() {
    driver.get("http://localhost:8080/administrator/index.php?controller=AdminLogin&token=6f8e295c6f145407a04731672a4f8b2a");
    driver.manage().window().setSize(new Dimension(1192, 700));
    System.out.println("{ASSESSOR}:LoginPage:doLogin");
    driver.findElement(By.id("email")).sendKeys("admin@prestashop.com");
    driver.findElement(By.id("passwd")).sendKeys("password");
    driver.findElement(By.cssSelector(".ladda-label")).click();
    System.out.println("{ASSESSOR}:DashboardPage:hoverCatalog");
    {
      WebElement element = driver.findElement(By.linkText("Catalog"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    System.out.println("{ASSESSOR}:DashboardPage:clickProductAttributes");
    driver.findElement(By.linkText("Product Attributes")).click();
    System.out.println("{ASSESSOR}:ProductAttributesPage:clickAddNewAttribute");
    driver.findElement(By.cssSelector("#page-header-desc-attribute_group-new_attribute_group > .process-icon-new")).click();
    System.out.println("{ASSESSOR}:NewAttributePage:changeName");
    driver.findElement(By.id("name_1")).sendKeys("Quantity");
    System.out.println("{ASSESSOR}:NewAttributePage:changePublicName");
    driver.findElement(By.id("public_name_1")).sendKeys("Qnt");
    System.out.println("{ASSESSOR}:NewAttributePage:ClickSave");
    driver.findElement(By.cssSelector(".process-icon-save")).click();
    System.out.println("{ASSESSOR}:ProductAttributesPage:getData");
    assertThat(driver.findElement(By.cssSelector(".alert:nth-child(1)")).getText(), is("×\\\\nSuccessful creation"));
    System.out.println("{ASSESSOR}:ProductAttributesPage:SignOut");
    driver.findElement(By.cssSelector(".employee_name")).click();
    driver.findElement(By.id("header_logout")).click();
  }
  @Test
  public void addNewFeatures() {
    driver.get("http://localhost:8080/administrator/index.php?controller=AdminLogin&token=6f8e295c6f145407a04731672a4f8b2a");
    driver.manage().window().setSize(new Dimension(1189, 700));
    System.out.println("{ASSESSOR}:LoginPage:doLogin");
    driver.findElement(By.id("email")).sendKeys("admin@prestashop.com");
    driver.findElement(By.id("passwd")).sendKeys("password");
    driver.findElement(By.name("submitLogin")).click();
    System.out.println("{ASSESSOR}:DashboardPage:hoverCatalog");
    {
      WebElement element = driver.findElement(By.linkText("Catalog"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    System.out.println("{ASSESSOR}:DashboardPage:clickProductFeatures");
    driver.findElement(By.linkText("Product Features")).click();
    System.out.println("{ASSESSOR}:ProductFeaturesPage:clickAddFeature");
    driver.findElement(By.cssSelector("#page-header-desc-feature-new_feature > .process-icon-new")).click();
    System.out.println("{ASSESSOR}:NewFeaturePage:changeName");
    driver.findElement(By.id("name_1")).sendKeys("Strong");
    System.out.println("{ASSESSOR}:NewFeaturePage:clickSave");
    driver.findElement(By.id("feature_form_submit_btn")).click();
    System.out.println("{ASSESSOR}:ProductFeaturesPage:getData");
    assertThat(driver.findElement(By.cssSelector(".alert:nth-child(1)")).getText(), is("×\\\\nSuccessful creation"));
    System.out.println("{ASSESSOR}:ProductFeaturesPage:SignOut");
    driver.findElement(By.cssSelector(".employee_name")).click();
    driver.findElement(By.id("header_logout")).click();
  }
  @Test
  public void addNewProductWithTax() {
    driver.get("http://localhost:8080/administrator/index.php?controller=AdminLogin&token=6f8e295c6f145407a04731672a4f8b2a");
    driver.manage().window().setSize(new Dimension(1185, 700));
    System.out.println("{ASSESSOR}:LoginPage:doLogin");
    driver.findElement(By.id("email")).sendKeys("admin@prestashop.com");
    driver.findElement(By.id("passwd")).sendKeys("password");
    driver.findElement(By.name("submitLogin")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".employee_avatar_small > .imgm"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    System.out.println("{ASSESSOR}:DashboardPage:hoverCatalog");
    {
      WebElement element = driver.findElement(By.linkText("Catalog"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    System.out.println("{ASSESSOR}:DashboardPage:clickProducts");
    driver.findElement(By.linkText("Products")).click();
    System.out.println("{ASSESSOR}:ProductsPage:clickAddNewProduct");
    driver.findElement(By.cssSelector("#page-header-desc-product-new_product > .process-icon-new")).click();
    System.out.println("{ASSESSOR}:NewProductPage:clickPrices");
    driver.findElement(By.id("link-Prices")).click();
    System.out.println("{ASSESSOR}:NewProductPage:changePreTaxRetailPrice");
    driver.findElement(By.id("priceTE")).sendKeys("10");
    System.out.println("{ASSESSOR}:NewProductPage:getData");
    {
      String value = driver.findElement(By.id("priceTI")).getAttribute("value");
      assertThat(value, is("12.20"));
    }
    System.out.println("{ASSESSOR}:NewProductPage:SignOut");
    driver.findElement(By.cssSelector(".employee_name")).click();
    driver.findElement(By.id("header_logout")).click();
  }
  @Test
  public void addNewProductWithTax10() {
    driver.get("http://localhost:8080/administrator/index.php?controller=AdminLogin&token=6f8e295c6f145407a04731672a4f8b2a");
    driver.manage().window().setSize(new Dimension(1171, 700));
    System.out.println("{ASSESSOR}:LoginPage:doLogin");
    driver.findElement(By.id("email")).sendKeys("admin@prestashop.com");
    driver.findElement(By.id("passwd")).sendKeys("password");
    driver.findElement(By.cssSelector(".ladda-label")).click();
    System.out.println("{ASSESSOR}:DashboardPage:hoverCatalog");
    {
      WebElement element = driver.findElement(By.linkText("Catalog"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    System.out.println("{ASSESSOR}:ProductsPage:clickAddNewProduct");
    driver.findElement(By.linkText("Products")).click();
    driver.findElement(By.cssSelector("#page-header-desc-product-new_product > .process-icon-new")).click();
    System.out.println("{ASSESSOR}:NewProductPage:clickPrices");
    driver.findElement(By.id("link-Prices")).click();
    System.out.println("{ASSESSOR}:NewProductPage:changePreTaxRetailPrice");
    driver.findElement(By.cssSelector("#product-prices > .form-group:nth-child(5)")).click();
    driver.findElement(By.id("priceTE")).sendKeys("10");
    System.out.println("{ASSESSOR}:NewProductPage:changeTaxRule");
    {
      WebElement dropdown = driver.findElement(By.id("id_tax_rules_group"));
      dropdown.findElement(By.xpath("//option[. = 'IT Reduced Rate (10%)']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(5)")).click();
    {
      String value = driver.findElement(By.id("priceTI")).getAttribute("value");
      assertThat(value, is("11.00"));
    }
    System.out.println("{ASSESSOR}:NewProductPage:getData");
    System.out.println("{ASSESSOR}:NewProductPage:SignOut");
    driver.findElement(By.cssSelector(".employee_name")).click();
    driver.findElement(By.id("header_logout")).click();
  }
  @Test
  public void addNewState() {
    driver.get("http://localhost:8080/administrator/index.php?controller=AdminLogin&token=6f8e295c6f145407a04731672a4f8b2a");
    driver.manage().window().setSize(new Dimension(1182, 700));
    driver.findElement(By.id("email")).sendKeys("admin@prestashop.com");
    driver.findElement(By.id("passwd")).sendKeys("password");
    driver.findElement(By.cssSelector(".ladda-label")).click();
    System.out.println("{ASSESSOR}:DashboardPage:hoverLocalization");
    {
      WebElement element = driver.findElement(By.linkText("Localization"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    System.out.println("{ASSESSOR}:DashboardPage:clickStates");
    driver.findElement(By.linkText("States")).click();
    System.out.println("{ASSESSOR}:StatesPage:clickAddNewState");
    driver.findElement(By.cssSelector("#page-header-desc-state-new_state > div")).click();
    System.out.println("{ASSESSOR}:NewStatePage:changeName");
    driver.findElement(By.id("name")).sendKeys("Liguria");
    System.out.println("{ASSESSOR}:NewStatePage:changeISOCode");
    driver.findElement(By.id("iso_code")).sendKeys("1121");
    System.out.println("{ASSESSOR}:NewStatePage:changeCountry");
    driver.findElement(By.id("id_country")).click();
    driver.findElement(By.cssSelector("#id_country > option:nth-child(4)")).click();
    System.out.println("{ASSESSOR}:NewStatePage:changeZone");
    {
      WebElement dropdown = driver.findElement(By.id("id_zone"));
      dropdown.findElement(By.xpath("//option[. = 'Europe']")).click();
    }
    driver.findElement(By.cssSelector("#id_zone > option:nth-child(4)")).click();
    System.out.println("{ASSESSOR}:NewStatePage:clickSave");
    driver.findElement(By.id("state_form_submit_btn")).click();
    System.out.println("{ASSESSOR}:StatesPage:getData");
    assertThat(driver.findElement(By.cssSelector(".alert-success:nth-child(1)")).getText(), is("×\\\\nSuccessful creation"));
    System.out.println("{ASSESSOR}:StatesPage:SignOut");
    driver.findElement(By.cssSelector(".employee_name > .string-short")).click();
    driver.findElement(By.id("header_logout")).click();
  }
  @Test
  public void editProduct() {
    driver.get("http://localhost:8080/administrator/index.php?controller=AdminLogin&token=6f8e295c6f145407a04731672a4f8b2a");
    driver.manage().window().setSize(new Dimension(1184, 700));
    System.out.println("{ASSESSOR}:LoginPage:doLogin");
    driver.findElement(By.id("email")).sendKeys("admin@prestashop.com");
    driver.findElement(By.id("passwd")).sendKeys("password");
    driver.findElement(By.name("submitLogin")).click();
    System.out.println("{ASSESSOR}:DashboardPage:hoverCatalog");
    System.out.println("{ASSESSOR}:DashboardPage:clickProducts");
    {
      WebElement element = driver.findElement(By.linkText("Catalog"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Products")).click();
    System.out.println("{ASSESSOR}:ProductsPage:clickBlueJacket3");
    driver.findElement(By.cssSelector("#tr__10_0 .edit")).click();
    System.out.println("{ASSESSOR}:EditProductPage:changeName");
    driver.findElement(By.id("name_1")).sendKeys("Deep Blue Jacket");
    System.out.println("{ASSESSOR}:EditProductPage:clickSave");
    driver.findElement(By.cssSelector(".panel-footer:nth-child(22) > .btn:nth-child(2) > .process-icon-save")).click();
    js.executeScript("window.scrollTo(0,308.79998779296875)");
    System.out.println("{ASSESSOR}:ProductsPage:getData");
    assertThat(driver.findElement(By.cssSelector(".alert-success:nth-child(1)")).getText(), is("×\\\\nSuccessful update"));
    System.out.println("{ASSESSOR}:ProductsPage:SignOut");
    driver.findElement(By.cssSelector(".employee_name")).click();
    driver.findElement(By.id("header_logout")).click();
  }
}
