package TestCases.PO;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class NewProductPage {

    WebDriver driver;

    JavascriptExecutor js;

    Map<String, Object> vars;

    public NewProductPage(WebDriver driver, JavascriptExecutor js, Map<String, Object> vars) {
        this.driver = driver;
        this.js = js;
        this.vars = vars;
    }

    public void clickSave(String key1) {
        By elem = By.name("submitAddproduct");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void changeName(String key1) {
        By elem = By.id("name_1");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key1);
        clickSave(key1);
    }

    public void getData() {
        By elem = By.cssSelector("ol > li:nth-child(1)");
        MyUtils.WaitForElementLoaded(driver, elem);
    }

    public void clickSave_1() {
        By elem = By.cssSelector(".panel-footer:nth-child(22) > .btn:nth-child(2) > .process-icon-save");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        js.executeScript("window.scrollTo(0,175.1999969482422)");
        getData();
    }

    public String set_CSSSELECTOR_ollinth_child1() {
        By elem = By.cssSelector("ol > li:nth-child(1)");
        MyUtils.WaitForElementLoaded(driver, elem);
        return driver.findElement(elem).getText();
    }

    public void click_CSSSELECTOR_employee_namestring_short() {
        By elem = By.cssSelector(".employee_name > .string-short");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_ID_header_logout() {
        By elem = By.id("header_logout");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void SignOut(boolean key1, boolean key2, boolean key3) {
        if (key1 != false)
            click_CSSSELECTOR_employee_namestring_short();
        if (key2 != false)
            click_ID_header_logout();
        if (key3 != false)
            click_CSSSELECTOR_employee_name();
    }
    public void changePreTaxRetailPrice(String key1) {
        By elem = By.id("priceTE");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).clear();
        driver.findElement(elem).sendKeys(key1);
    }

    public void clickPrices(String key1) {
        By elem = By.id("link-Prices");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        changePreTaxRetailPrice(key1);
    }

    public String set_ID_priceTI() {
        By elem = By.id("priceTI");
        MyUtils.WaitForElementLoaded(driver, elem);
        String value = driver.findElement(elem).getAttribute("value");
        return value;
    }

    public void click_CSSSELECTOR_employee_name() {
        By elem = By.cssSelector(".employee_name");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void changePreTaxRetailPrice_1() {
        By elem = By.cssSelector("#product-prices > .form-group:nth-child(5)");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void changeTaxRule(String key2) {
        By elem = By.id("id_tax_rules_group");
        MyUtils.WaitForElementLoaded(driver, elem);
        WebElement dropdown = driver.findElement(elem);
        elem = By.xpath("//option[contains(text(), '" + key2 + "')]");
        MyUtils.WaitForElementLoaded(driver, elem);
        dropdown.findElement(elem).click();
    }


    public void clickPrices_1(String key1, String key2) {
        By elem = By.id("link-Prices");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        changePreTaxRetailPrice(key1);
        changeTaxRule(key2);
    }

    public void getData_1() {
        click_CSSSELECTOR_employee_name();
        click_ID_header_logout();
    }
}
