package TestCases.PO;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class ProductsPage {

    WebDriver driver;

    JavascriptExecutor js;

    Map<String, Object> vars;

    public ProductsPage(WebDriver driver, JavascriptExecutor js, Map<String, Object> vars) {
        this.driver = driver;
        this.js = js;
        this.vars = vars;
    }

    public void clickAddNewProduct() {
        By elem = By.cssSelector("#page-header-desc-product-new_product > .process-icon-new");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        js.executeScript("window.scrollTo(0,0)");
    }

    public String getData() {
        By elem = By.cssSelector(".alert-success:nth-child(1)");
        MyUtils.WaitForElementLoaded(driver, elem);
        return driver.findElement(elem).getText();
    }

    public void click_CSSSELECTOR_employee_name() {
        By elem = By.cssSelector(".employee_name");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_ID_header_logout() {
        By elem = By.id("header_logout");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void SignOut() {
        click_CSSSELECTOR_employee_name();
        click_ID_header_logout();
    }

    public void click_CSSSELECTOR_page_header_desc_product_new_productdiv() {
        By elem = By.cssSelector("#page-header-desc-product-new_product > div");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
        {
            elem = By.linkText("Help");
            MyUtils.WaitForElementLoaded(driver, elem);
            WebElement element = driver.findElement(elem);
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        js.executeScript("window.scrollTo(0,0)");
    }

    public void clickAddNewProduct_1() {
        click_CSSSELECTOR_page_header_desc_product_new_productdiv();
    }

    public void clickAddNewProduct_2() {
        By elem = By.cssSelector("#page-header-desc-product-new_product > .process-icon-new");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void click_LINKTEXT_Products() {
        By elem = By.linkText("Products");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }

    public void clickAddNewProduct_3() {
        click_LINKTEXT_Products();
        clickAddNewProduct_2();
    }

    public void clickBlueJacket3() {
        By elem = By.cssSelector("#tr__10_0 .edit");
        MyUtils.WaitForElementLoaded(driver, elem);
        driver.findElement(elem).click();
    }
}
