package TestCases;

import org.junit.BeforeClass;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import TestCases.PO.*;

public class TestCases {

    private WebDriver driver;

    private Map<String, Object> vars;

    private JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void addNewProduct() {
        driver.get("http://localhost:8080/administrator/index.php?controller=AdminLogin&token=6f8e295c6f145407a04731672a4f8b2a");
        driver.manage().window().setSize(new Dimension(1164, 700));
        LoginPage _LoginPage = new LoginPage(driver, js, vars);
        _LoginPage.doLogin("admin@prestashop.com", "password", true, false, false);
        DashboardPage _DashboardPage = new DashboardPage(driver, js, vars);
        _DashboardPage.hoverCatalog(true, false);
        ProductsPage _ProductsPage = new ProductsPage(driver, js, vars);
        _ProductsPage.clickAddNewProduct();
        NewProductPage _NewProductPage = new NewProductPage(driver, js, vars);
        _NewProductPage.changeName("Blue Jacket3");
        assertThat(_ProductsPage.getData(), is("×\nSuccessful creation"));
        _ProductsPage.SignOut();
    }

    @Test
    public void addEmptyProduct() {
        driver.get("http://localhost:8080/administrator/index.php?controller=AdminLogin&token=6f8e295c6f145407a04731672a4f8b2a");
        driver.manage().window().setSize(new Dimension(1179, 700));
        LoginPage _LoginPage = new LoginPage(driver, js, vars);
        _LoginPage.doLogin("admin@prestashop.com", "password", false, true, false);
        DashboardPage _DashboardPage = new DashboardPage(driver, js, vars);
        _DashboardPage.hoverCatalog(false, true);
        ProductsPage _ProductsPage = new ProductsPage(driver, js, vars);
        _ProductsPage.clickAddNewProduct_1();
        NewProductPage _NewProductPage = new NewProductPage(driver, js, vars);
        _NewProductPage.clickSave_1();
        assertThat(_NewProductPage.set_CSSSELECTOR_ollinth_child1(), is("This link_rewrite field is required at least in English (English)"));
        _NewProductPage.SignOut(true, true, false);
    }

    @Test
    public void addEmptyFeature() {
        driver.get("http://localhost:8080/administrator/index.php?controller=AdminLogin&token=6f8e295c6f145407a04731672a4f8b2a");
        driver.manage().window().setSize(new Dimension(1190, 700));
        LoginPage _LoginPage = new LoginPage(driver, js, vars);
        _LoginPage.doLogin("admin@prestashop.com", "password", true, false, false);
        DashboardPage _DashboardPage = new DashboardPage(driver, js, vars);
        _DashboardPage.hoverCatalog_1();
        ProductFeaturesPage _ProductFeaturesPage = new ProductFeaturesPage(driver, js, vars);
        _ProductFeaturesPage.clickAddFeature();
        NewFeaturePage _NewFeaturePage = new NewFeaturePage(driver, js, vars);
        _NewFeaturePage.clickSave();
        assertThat(_NewFeaturePage.set_CSSSELECTOR_alert_danger(), is("×\nThe field name is required at least in English (English)."));
        _NewFeaturePage.SignOut();
    }

    @Test
    public void addEmptyState() {
        driver.get("http://localhost:8080/administrator/index.php?controller=AdminLogin&token=6f8e295c6f145407a04731672a4f8b2a");
        driver.manage().window().setSize(new Dimension(1215, 700));
        LoginPage _LoginPage = new LoginPage(driver, js, vars);
        _LoginPage.doLogin("admin@prestashop.com", "password", true, false, false);
        DashboardPage _DashboardPage = new DashboardPage(driver, js, vars);
        _DashboardPage.hoverLocalization();
        StatesPage _StatesPage = new StatesPage(driver, js, vars);
        _StatesPage.clickAddNewState();
        NewStatePage _NewStatePage = new NewStatePage(driver, js, vars);
        _NewStatePage.clickSave();
        assertThat(_NewStatePage.set_CSSSELECTOR_ollinth_child2(), is("The name field is required."));
        _NewStatePage.SignOut();
    }

    @Test
    public void addNewAttribute() {
        driver.get("http://localhost:8080/administrator/index.php?controller=AdminLogin&token=6f8e295c6f145407a04731672a4f8b2a");
        driver.manage().window().setSize(new Dimension(1192, 700));
        LoginPage _LoginPage = new LoginPage(driver, js, vars);
        _LoginPage.doLogin("admin@prestashop.com", "password", false, true, false);
        DashboardPage _DashboardPage = new DashboardPage(driver, js, vars);
        _DashboardPage.hoverCatalog_2();
        ProductAttributesPage _ProductAttributesPage = new ProductAttributesPage(driver, js, vars);
        _ProductAttributesPage.clickAddNewAttribute();
        NewAttributePage _NewAttributePage = new NewAttributePage(driver, js, vars);
        _NewAttributePage.changeName("Quantity", "Qnt");
        assertThat(_ProductAttributesPage.getData(), is("×\nSuccessful creation"));
        _ProductAttributesPage.SignOut();
    }

    @Test
    public void addNewFeatures() {
        driver.get("http://localhost:8080/administrator/index.php?controller=AdminLogin&token=6f8e295c6f145407a04731672a4f8b2a");
        driver.manage().window().setSize(new Dimension(1189, 700));
        LoginPage _LoginPage = new LoginPage(driver, js, vars);
        _LoginPage.doLogin("admin@prestashop.com", "password", true, false, false);
        DashboardPage _DashboardPage = new DashboardPage(driver, js, vars);
        _DashboardPage.hoverCatalog_1();
        ProductFeaturesPage _ProductFeaturesPage = new ProductFeaturesPage(driver, js, vars);
        _ProductFeaturesPage.clickAddFeature_1();
        NewFeaturePage _NewFeaturePage = new NewFeaturePage(driver, js, vars);
        _NewFeaturePage.changeName("Strong");
        assertThat(_ProductFeaturesPage.getData(), is("×\nSuccessful creation"));
        _ProductFeaturesPage.SignOut();
    }

    @Test
    public void addNewProductWithTax() {
        driver.get("http://localhost:8080/administrator/index.php?controller=AdminLogin&token=6f8e295c6f145407a04731672a4f8b2a");
        driver.manage().window().setSize(new Dimension(1185, 700));
        LoginPage _LoginPage = new LoginPage(driver, js, vars);
        _LoginPage.doLogin("admin@prestashop.com", "password", false, false, true);
        DashboardPage _DashboardPage = new DashboardPage(driver, js, vars);
        _DashboardPage.hoverCatalog_3();
        ProductsPage _ProductsPage = new ProductsPage(driver, js, vars);
        _ProductsPage.clickAddNewProduct_2();
        NewProductPage _NewProductPage = new NewProductPage(driver, js, vars);
        _NewProductPage.clickPrices("10");
        assertThat(_NewProductPage.set_ID_priceTI(), is("12.20"));
        _NewProductPage.SignOut(true, true, false);
    }

    @Test
    public void addNewProductWithTax10() {
        driver.get("http://localhost:8080/administrator/index.php?controller=AdminLogin&token=6f8e295c6f145407a04731672a4f8b2a");
        driver.manage().window().setSize(new Dimension(1171, 700));
        LoginPage _LoginPage = new LoginPage(driver, js, vars);
        _LoginPage.doLogin("admin@prestashop.com", "password", false, true, false);
        DashboardPage _DashboardPage = new DashboardPage(driver, js, vars);
        _DashboardPage.hoverCatalog_4();
        ProductsPage _ProductsPage = new ProductsPage(driver, js, vars);
        _ProductsPage.clickAddNewProduct_3();
        NewProductPage _NewProductPage = new NewProductPage(driver, js, vars);
        _NewProductPage.clickPrices_1("10", "IT Reduced Rate (10%)");
        assertThat(_NewProductPage.set_ID_priceTI(), is("11.00"));
        _NewProductPage.getData_1();
    }

    @Test
    public void addNewState() {
        driver.get("http://localhost:8080/administrator/index.php?controller=AdminLogin&token=6f8e295c6f145407a04731672a4f8b2a");
        driver.manage().window().setSize(new Dimension(1182, 700));
        AutoPo _AutoPo = new AutoPo(driver, js, vars);
        _AutoPo.set_ID_email("admin@prestashop.com", "password");
        DashboardPage _DashboardPage = new DashboardPage(driver, js, vars);
        _DashboardPage.hoverLocalization();
        StatesPage _StatesPage = new StatesPage(driver, js, vars);
        _StatesPage.clickAddNewState_1();
        NewStatePage _NewStatePage = new NewStatePage(driver, js, vars);
        _NewStatePage.changeName("Liguria", "1121", "Europe");
        assertThat(_StatesPage.getData(), is("×\nSuccessful creation"));
        _StatesPage.SignOut();
    }

    @Test
    public void editProduct() {
        driver.get("http://localhost:8080/administrator/index.php?controller=AdminLogin&token=6f8e295c6f145407a04731672a4f8b2a");
        driver.manage().window().setSize(new Dimension(1184, 700));
        LoginPage _LoginPage = new LoginPage(driver, js, vars);
        _LoginPage.doLogin("admin@prestashop.com", "password", true, false, false);
        DashboardPage _DashboardPage = new DashboardPage(driver, js, vars);
        _DashboardPage.hoverCatalog(true, false);
        ProductsPage _ProductsPage = new ProductsPage(driver, js, vars);
        _ProductsPage.clickBlueJacket3();
        EditProductPage _EditProductPage = new EditProductPage(driver, js, vars);
        _EditProductPage.changeName("Deep Blue Jacket");
        assertThat(_ProductsPage.getData(), is("×\nSuccessful update"));
        _ProductsPage.SignOut();
    }
}
